version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - postgres-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "946@ada.br"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "2345:80"
    depends_on:
      - postgres
    networks:
      - postgres-network
  wiremock-server:
    image: wiremock/wiremock
    container_name: wiremock
    volumes:
      - ./stubs/token:/home/wiremock
    command: "--global-response-templating --verbose"
    ports:
      - "8282:8080"

networks:
  postgres-network:
    driver: bridge